name: lint_and_test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        isort --check-only --profile=google $(git ls-files '*.py')
        black --check --line-length=120 $(git ls-files '*.py')
        pylint --rcfile .pylintrc $(git ls-files '*.py')
    - name: Run all tests
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      run: |
        python -m unittest discover --pattern test_*.py --failfast -v
